version: "3.7"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=mastering_flask
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    restart: always
    build: .
    ports:
      - '5001:5001'
    volumes:
      - .:/app
    depends_on:
      - db
volumes:
  postgres_data:
  